module.exports = {
  representedByAgent: ['select[id$="representedByAgentDropdownlist"]'],
  title: ['select[id$="titleDropDownList"]'],
  gender: ['select[id$="genderDropDownList"]'],
  countryOfBirth: ['select[id$="personDetails_CountryDropDownList"]', 'select[id$="countryOfBirthDropDownList"]'],
  passportCitizenship: ['select[id$="passportCountryDropDownList"]', 'select[id$="passportCitizenshipDropDownList"]', 'select[id$="nationalityDropDownList"]'],
  addressCountry: ['select[id$="address_countryDropDownList"]'],
  communicationMethod: ['select[id$="communicationMethodDropDownList"]'],
  hasCreditCard: ['select[id$="hasCreditCardDropDownlist"]'],
  idType: ['select[id$="otherIdentificationDropdownlist"]', 'select[id$="identityDocumentTypeDropDownList"]'],
  renalDialysis: ['select[id$="renalDialysisDropDownList"]'],
  activeTb: ['select[id$="tuberculosisDropDownList"]', 'select[id$="activeTbDropDownList"]'],
  cancer: ['select[id$="cancerDropDownList"]'],
  heartDisease: ['select[id$="heartDiseaseDropDownList"]'],
  disability: ['select[id$="disabilityDropDownList"]'],
  hospitalisation: ['select[id$="hospitalisationDropDownList"]'],
  residentialCare: ['select[id$="residentailCareDropDownList"]', 'select[id$="residentialCareDropDownList"]'],
  pregnancy: ['select[id$="pregnancyStatusDropDownList"]'],
  tbRisk: ['select[id$="tbRiskDropDownList"]'],
  imprisonment5Years: ['select[id$="imprisonment5YearsDropDownList"]'],
  imprisonment12Months: ['select[id$="imprisonment12MonthsDropDownList"]'],
  deported: ['select[id$="deportedDropDownList"]'],
  removalOrder: ['select[id$="removalOrderDropDownList"]'],
  charged: ['select[id$="chargedDropDownList"]'],
  convicted: ['select[id$="convictedDropDownList"]'],
  underInvestigation: ['select[id$="underInvestigationDropDownList"]'],
  excluded: ['select[id$="excludedDropDownList"]'],
  removed: ['select[id$="removedDropDownList"]'],
  previousWhsVisa: ['select[id$="previousWhsPermitVisaDropDownList"]', 'select[id$="previousWorkingHolidayVisaDropDownList"]'],
  sufficientFundsHoliday: ['select[id$="sufficientFundsHolidayDropDownList"]'],
  beenToNz: ['select[id$="beenToNzDropDownList"]'],
  sufficientFundsOnwardTicket: ['select[id$="sufficientFundsOnwardTicketDropDownList"]'],
  meetSchemeRequirements: ['select[id$="readRequirementsDropDownList"]'],
  lengthOfStay: ['select[id$="lengthOfStayDropDownList"]']
};