module.exports = {
  username: ['input[name="username"]'],
  password: ['input[name="password"]'],
  familyName: ['[id$="familyNameTextBox"]'],
  givenName1: ['[id$="givenName1TextBox"]'],
  givenName2: ['[id$="givenName2TextBox"]'],
  givenName3: ['[id$="givenName3TextBox"]'],
  otherNames: ['[id$="otherNamesTextBox"]'],
  dateOfBirth: ['[id$="dateOfBirthDatePicker_DatePicker"]', '[id$="dateOfBirthTextBox"]'],
  passportNumber: ['[id$="passportNumberTextBox"]'],
  confirmPassportNumber: ['[id$="confirmPassportNumberTextBox"]'],
  passportExpiry: ['[id$="passportExpiryDateDatePicker_DatePicker"]'],
  idExpiryDate: ['[id$="identityDocumentExpiryDateTextBox"]', '[id$="idExpiryDateTextBox"]'],
  idIssueDate: ['[id$="otherIssueDateDatePicker_DatePicker"]', '[id$="identityDocumentIssueDateTextBox"]', '[id$="idIssueDateTextBox"]'],
  streetNumber: ['[id$="streetNumberTextbox"]', '[id$="streetNumberTextBox"]'],
  streetName: ['[id$="address1TextBox"]'],
  suburb: ['[id$="suburbTextBox"]'],
  city: ['[id$="cityTextBox"]'],
  postalCode: ['[id$="postalCodeTextBox"]', '[id$="postCodeTextBox"]'],
  phoneDaytime: ['[id$="daytimePhoneTextBox"]'],
  phoneMobile: ['[id$="mobilePhoneTextBox"]'],
  email: ['[id$="emailTextBox"]'],
  medicalDetails: ['[id$="medicalConditionsTextBox"]'],
  characterDetails: ['[id$="characterDetailsTextBox"]'],
  travelDate: ['[id$="intendedTravelDateDatePicker_DatePicker"]'],
  beenToNzWhen: ['[id$="beenToNzDateDatePicker_DatePicker"]', '[id$="whenInNzDatePicker_DatePicker"]'],
  payerName: ['[id$="payerNameTextBox"]', '[id$="PayerNameTextBox"]', '[id$="payerName"]', '[id$="txtPayerName"]', '[id$="cardHolderNameTextBox"]', '[id$="nameOnCardTextBox"]', '[id$="payerFullNameTextBox"]']
};